### ISSUE TITLE
Add Emperors' Blessing for Marauder Bomber/Destroyer

### ISSUE THREAD

**Issue by zopha** [BSData/aeronautica-imperialis#46]
Coming in the next WD.

![image](https://user-images.githubusercontent.com/1666415/141458008-baa99580-577a-4350-b1be-a1fe50a7090c.png)

Not sure how this works myself, does it add 4-0-0 or 4-4-4 when you use it?

**Comment by shaner11** [comment]
My best guess is it would only add to the first value, otherwise that would have to be a scary huge bomb. That still makes it 8-0-0 on a destroyer and a whopping !12!-0-0 on a bomber.

**Comment by evanh** [comment]
Looking at the rules, they are written in a way to suggest that if a weapon has a 0 at a range, it can't shoot that weapon at that range. Since this upgrade happens "when firing" the Bomb Bay, you would have to be eligible to fire it in the first place before you could add the buff.

Which I think is how they intended it anyways.
